### ISSUE TITLE
Create travis ci build

### ISSUE THREAD

**Issue by mcraveiro** [avao/Qart#4]
Can you please go to travis[1] and add a build for the project? Don't worry about the travis file etc, I'll do that locally. I just can't add a build for a project I don't own it seems.

[1] https://travis-ci.org/

**Comment by avao** [comment]
It is on appveyor, why do you need travis?

**Comment by mcraveiro** [comment]
To make sure the Linux build doesn't break going forward.

**Comment by avao** [comment]
done.
